# version: "3.5"
services:
    app:
        build:
            context: .
            target: dev
        container_name: smart-backend
        environment:
            - MONGO_URI=mongodb://db:27017
            - JWT_SECRET_KEY=secret
            - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
            - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
        ports:
            - "3000:3000"
        depends_on:
            - db

        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

    db:
        image: mongo
        container_name: smart-db
        restart: always
        ports:
            - "3001:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
