name: Build and Push to Docker Hub

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: sourav2004/smart-backend:latest # Replace with your Docker Hub username and repository

            - name: Verify Pushed Image
              run: docker pull sourav2004/smart-backend:latest # Replace with your Docker Hub username and repository

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      sudo docker pull sourav2004/smart-backend:latest
                      sudo docker stop backend-app || true
                      sudo docker rm backend-app || true
                      sudo docker run -d --name backend-app -e MONGO_URI=${{secrets.MONGO_URI}} -e JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}} -e CLOUDINARY_CLOUD_NAME=${{secrets.CLOUDINARY_CLOUD_NAME}} -e CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}} -e CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}} -p 3005:3000 sourav2004/smart-backend:latest
