name: Build and Push to Docker Hub

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: sourav2004/smart-backend:latest # Replace with your Docker Hub username and repository

            - name: Verify Pushed Image
              run: docker pull sourav2004/smart-backend:latest # Replace with your Docker Hub username and repository
